language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer global require "fxp/composer-asset-plugin:~1.4.4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install --prefer-dist --no-interaction

script:
  - phpunit
